// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChatRoomProtocol.proto

package optic_fusion1.common.protos;

public final class ChatRoomProtocol {
  private ChatRoomProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HandshakePacket_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HandshakePacket_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PongPacket_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PongPacket_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ErrorPacket_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ErrorPacket_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Packet_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Packet_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026ChatRoomProtocol.proto\"=\n\017HandshakePac" +
      "ket\022*\n\020protocol_version\030\002 \002(\0162\020.Protocol" +
      "Version\"_\n\nPongPacket\0221\n\027server_protocol" +
      "_version\030\001 \002(\0162\020.ProtocolVersion\022\036\n\026conn" +
      "ected_client_count\030\002 \002(\005\"v\n\013ErrorPacket\022" +
      "%\n\nerror_type\030\001 \002(\0162\021.ErrorPacket.Type\022\023" +
      "\n\013description\030\002 \002(\t\"+\n\004Type\022\026\n\022CONNECTIO" +
      "N_REFUSED\020\000\022\013\n\007UNKNOWN\020\001\"\342\001\n\006Packet\022!\n\013p" +
      "acket_type\030\001 \002(\0162\014.Packet.Type\022*\n\016handsh" +
      "ake_data\030\003 \001(\0132\020.HandshakePacketH\000\022 \n\tpo" +
      "ng_data\030\004 \001(\0132\013.PongPacketH\000\022\"\n\nerror_da" +
      "ta\030\005 \001(\0132\014.ErrorPacketH\000\"4\n\004Type\022\r\n\tHAND" +
      "SHAKE\020\000\022\010\n\004PING\020\001\022\010\n\004PONG\020\002\022\t\n\005ERROR\020\003B\r" +
      "\n\013packet_data*3\n\017ProtocolVersion\022\017\n\013VERS" +
      "ION_000\020\000\022\017\n\013VERSION_001\020\001B1\n\033optic_fusi" +
      "on1.common.protosB\020ChatRoomProtocolP\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_HandshakePacket_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_HandshakePacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HandshakePacket_descriptor,
        new java.lang.String[] { "ProtocolVersion", });
    internal_static_PongPacket_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PongPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PongPacket_descriptor,
        new java.lang.String[] { "ServerProtocolVersion", "ConnectedClientCount", });
    internal_static_ErrorPacket_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ErrorPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ErrorPacket_descriptor,
        new java.lang.String[] { "ErrorType", "Description", });
    internal_static_Packet_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Packet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Packet_descriptor,
        new java.lang.String[] { "PacketType", "HandshakeData", "PongData", "ErrorData", "PacketData", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
