// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChatRoomProtocol.proto

package optic_fusion1.common.protos;

public interface HandshakeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HandshakeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required .ProtocolVersion protocol_version = 1;</code>
   * @return Whether the protocolVersion field is set.
   */
  boolean hasProtocolVersion();
  /**
   * <code>required .ProtocolVersion protocol_version = 1;</code>
   * @return The protocolVersion.
   */
  optic_fusion1.common.protos.ProtocolVersion getProtocolVersion();

  /**
   * <code>required bytes rsa_public_key = 2;</code>
   * @return Whether the rsaPublicKey field is set.
   */
  boolean hasRsaPublicKey();
  /**
   * <code>required bytes rsa_public_key = 2;</code>
   * @return The rsaPublicKey.
   */
  com.google.protobuf.ByteString getRsaPublicKey();
}
