// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChatRoomProtocol.proto

package optic_fusion1.common.protos;

public interface HandshakeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HandshakeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The servers protocol version
   * </pre>
   *
   * <code>required .ProtocolVersion protocol_version = 1;</code>
   * @return Whether the protocolVersion field is set.
   */
  boolean hasProtocolVersion();
  /**
   * <pre>
   * The servers protocol version
   * </pre>
   *
   * <code>required .ProtocolVersion protocol_version = 1;</code>
   * @return The protocolVersion.
   */
  optic_fusion1.common.protos.ProtocolVersion getProtocolVersion();

  /**
   * <code>required string session_id = 2;</code>
   * @return Whether the sessionId field is set.
   */
  boolean hasSessionId();
  /**
   * <code>required string session_id = 2;</code>
   * @return The sessionId.
   */
  java.lang.String getSessionId();
  /**
   * <code>required string session_id = 2;</code>
   * @return The bytes for sessionId.
   */
  com.google.protobuf.ByteString
      getSessionIdBytes();

  /**
   * <code>required bytes hmac_key = 3;</code>
   * @return Whether the hmacKey field is set.
   */
  boolean hasHmacKey();
  /**
   * <code>required bytes hmac_key = 3;</code>
   * @return The hmacKey.
   */
  com.google.protobuf.ByteString getHmacKey();

  /**
   * <code>required bytes rsa_public_key = 4;</code>
   * @return Whether the rsaPublicKey field is set.
   */
  boolean hasRsaPublicKey();
  /**
   * <code>required bytes rsa_public_key = 4;</code>
   * @return The rsaPublicKey.
   */
  com.google.protobuf.ByteString getRsaPublicKey();

  /**
   * <code>required bool authentication_required = 5;</code>
   * @return Whether the authenticationRequired field is set.
   */
  boolean hasAuthenticationRequired();
  /**
   * <code>required bool authentication_required = 5;</code>
   * @return The authenticationRequired.
   */
  boolean getAuthenticationRequired();
}
