// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChatRoomProtocol.proto

package optic_fusion1.common.protos;

public interface HandshakePacketOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HandshakePacket)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required .ProtocolVersion protocol_version = 2;</code>
   * @return Whether the protocolVersion field is set.
   */
  boolean hasProtocolVersion();
  /**
   * <code>required .ProtocolVersion protocol_version = 2;</code>
   * @return The protocolVersion.
   */
  optic_fusion1.common.protos.ProtocolVersion getProtocolVersion();
}
