// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChatRoomProtocol.proto

package optic_fusion1.common.protos;

/**
 * <pre>
 * Server -&gt; Client
 * </pre>
 *
 * Protobuf type {@code HandshakeResponse}
 */
public final class HandshakeResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:HandshakeResponse)
    HandshakeResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use HandshakeResponse.newBuilder() to construct.
  private HandshakeResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private HandshakeResponse() {
    protocolVersion_ = 1;
    sessionId_ = "";
    hmacKey_ = com.google.protobuf.ByteString.EMPTY;
    rsaPublicKey_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new HandshakeResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private HandshakeResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();
              @SuppressWarnings("deprecation")
            optic_fusion1.common.protos.ProtocolVersion value = optic_fusion1.common.protos.ProtocolVersion.valueOf(rawValue);
            if (value == null) {
              unknownFields.mergeVarintField(1, rawValue);
            } else {
              bitField0_ |= 0x00000001;
              protocolVersion_ = rawValue;
            }
            break;
          }
          case 18: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000002;
            sessionId_ = bs;
            break;
          }
          case 26: {
            bitField0_ |= 0x00000004;
            hmacKey_ = input.readBytes();
            break;
          }
          case 34: {
            bitField0_ |= 0x00000008;
            rsaPublicKey_ = input.readBytes();
            break;
          }
          case 40: {
            bitField0_ |= 0x00000010;
            authenticationRequired_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return optic_fusion1.common.protos.ChatRoomProtocol.internal_static_HandshakeResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return optic_fusion1.common.protos.ChatRoomProtocol.internal_static_HandshakeResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            optic_fusion1.common.protos.HandshakeResponse.class, optic_fusion1.common.protos.HandshakeResponse.Builder.class);
  }

  private int bitField0_;
  public static final int PROTOCOL_VERSION_FIELD_NUMBER = 1;
  private int protocolVersion_;
  /**
   * <pre>
   * The servers protocol version
   * </pre>
   *
   * <code>required .ProtocolVersion protocol_version = 1;</code>
   * @return Whether the protocolVersion field is set.
   */
  @java.lang.Override public boolean hasProtocolVersion() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * The servers protocol version
   * </pre>
   *
   * <code>required .ProtocolVersion protocol_version = 1;</code>
   * @return The protocolVersion.
   */
  @java.lang.Override public optic_fusion1.common.protos.ProtocolVersion getProtocolVersion() {
    @SuppressWarnings("deprecation")
    optic_fusion1.common.protos.ProtocolVersion result = optic_fusion1.common.protos.ProtocolVersion.valueOf(protocolVersion_);
    return result == null ? optic_fusion1.common.protos.ProtocolVersion.VERSION_1 : result;
  }

  public static final int SESSION_ID_FIELD_NUMBER = 2;
  private volatile java.lang.Object sessionId_;
  /**
   * <code>required string session_id = 2;</code>
   * @return Whether the sessionId field is set.
   */
  @java.lang.Override
  public boolean hasSessionId() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>required string session_id = 2;</code>
   * @return The sessionId.
   */
  @java.lang.Override
  public java.lang.String getSessionId() {
    java.lang.Object ref = sessionId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        sessionId_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string session_id = 2;</code>
   * @return The bytes for sessionId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSessionIdBytes() {
    java.lang.Object ref = sessionId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sessionId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HMAC_KEY_FIELD_NUMBER = 3;
  private com.google.protobuf.ByteString hmacKey_;
  /**
   * <code>required bytes hmac_key = 3;</code>
   * @return Whether the hmacKey field is set.
   */
  @java.lang.Override
  public boolean hasHmacKey() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>required bytes hmac_key = 3;</code>
   * @return The hmacKey.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getHmacKey() {
    return hmacKey_;
  }

  public static final int RSA_PUBLIC_KEY_FIELD_NUMBER = 4;
  private com.google.protobuf.ByteString rsaPublicKey_;
  /**
   * <code>required bytes rsa_public_key = 4;</code>
   * @return Whether the rsaPublicKey field is set.
   */
  @java.lang.Override
  public boolean hasRsaPublicKey() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>required bytes rsa_public_key = 4;</code>
   * @return The rsaPublicKey.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getRsaPublicKey() {
    return rsaPublicKey_;
  }

  public static final int AUTHENTICATION_REQUIRED_FIELD_NUMBER = 5;
  private boolean authenticationRequired_;
  /**
   * <code>required bool authentication_required = 5;</code>
   * @return Whether the authenticationRequired field is set.
   */
  @java.lang.Override
  public boolean hasAuthenticationRequired() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>required bool authentication_required = 5;</code>
   * @return The authenticationRequired.
   */
  @java.lang.Override
  public boolean getAuthenticationRequired() {
    return authenticationRequired_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasProtocolVersion()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasSessionId()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasHmacKey()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasRsaPublicKey()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasAuthenticationRequired()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeEnum(1, protocolVersion_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, sessionId_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeBytes(3, hmacKey_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeBytes(4, rsaPublicKey_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeBool(5, authenticationRequired_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, protocolVersion_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, sessionId_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, hmacKey_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(4, rsaPublicKey_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, authenticationRequired_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof optic_fusion1.common.protos.HandshakeResponse)) {
      return super.equals(obj);
    }
    optic_fusion1.common.protos.HandshakeResponse other = (optic_fusion1.common.protos.HandshakeResponse) obj;

    if (hasProtocolVersion() != other.hasProtocolVersion()) return false;
    if (hasProtocolVersion()) {
      if (protocolVersion_ != other.protocolVersion_) return false;
    }
    if (hasSessionId() != other.hasSessionId()) return false;
    if (hasSessionId()) {
      if (!getSessionId()
          .equals(other.getSessionId())) return false;
    }
    if (hasHmacKey() != other.hasHmacKey()) return false;
    if (hasHmacKey()) {
      if (!getHmacKey()
          .equals(other.getHmacKey())) return false;
    }
    if (hasRsaPublicKey() != other.hasRsaPublicKey()) return false;
    if (hasRsaPublicKey()) {
      if (!getRsaPublicKey()
          .equals(other.getRsaPublicKey())) return false;
    }
    if (hasAuthenticationRequired() != other.hasAuthenticationRequired()) return false;
    if (hasAuthenticationRequired()) {
      if (getAuthenticationRequired()
          != other.getAuthenticationRequired()) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasProtocolVersion()) {
      hash = (37 * hash) + PROTOCOL_VERSION_FIELD_NUMBER;
      hash = (53 * hash) + protocolVersion_;
    }
    if (hasSessionId()) {
      hash = (37 * hash) + SESSION_ID_FIELD_NUMBER;
      hash = (53 * hash) + getSessionId().hashCode();
    }
    if (hasHmacKey()) {
      hash = (37 * hash) + HMAC_KEY_FIELD_NUMBER;
      hash = (53 * hash) + getHmacKey().hashCode();
    }
    if (hasRsaPublicKey()) {
      hash = (37 * hash) + RSA_PUBLIC_KEY_FIELD_NUMBER;
      hash = (53 * hash) + getRsaPublicKey().hashCode();
    }
    if (hasAuthenticationRequired()) {
      hash = (37 * hash) + AUTHENTICATION_REQUIRED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getAuthenticationRequired());
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static optic_fusion1.common.protos.HandshakeResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static optic_fusion1.common.protos.HandshakeResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static optic_fusion1.common.protos.HandshakeResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static optic_fusion1.common.protos.HandshakeResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static optic_fusion1.common.protos.HandshakeResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static optic_fusion1.common.protos.HandshakeResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static optic_fusion1.common.protos.HandshakeResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static optic_fusion1.common.protos.HandshakeResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static optic_fusion1.common.protos.HandshakeResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static optic_fusion1.common.protos.HandshakeResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static optic_fusion1.common.protos.HandshakeResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static optic_fusion1.common.protos.HandshakeResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(optic_fusion1.common.protos.HandshakeResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Server -&gt; Client
   * </pre>
   *
   * Protobuf type {@code HandshakeResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:HandshakeResponse)
      optic_fusion1.common.protos.HandshakeResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return optic_fusion1.common.protos.ChatRoomProtocol.internal_static_HandshakeResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return optic_fusion1.common.protos.ChatRoomProtocol.internal_static_HandshakeResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              optic_fusion1.common.protos.HandshakeResponse.class, optic_fusion1.common.protos.HandshakeResponse.Builder.class);
    }

    // Construct using optic_fusion1.common.protos.HandshakeResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      protocolVersion_ = 1;
      bitField0_ = (bitField0_ & ~0x00000001);
      sessionId_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      hmacKey_ = com.google.protobuf.ByteString.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000004);
      rsaPublicKey_ = com.google.protobuf.ByteString.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000008);
      authenticationRequired_ = false;
      bitField0_ = (bitField0_ & ~0x00000010);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return optic_fusion1.common.protos.ChatRoomProtocol.internal_static_HandshakeResponse_descriptor;
    }

    @java.lang.Override
    public optic_fusion1.common.protos.HandshakeResponse getDefaultInstanceForType() {
      return optic_fusion1.common.protos.HandshakeResponse.getDefaultInstance();
    }

    @java.lang.Override
    public optic_fusion1.common.protos.HandshakeResponse build() {
      optic_fusion1.common.protos.HandshakeResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public optic_fusion1.common.protos.HandshakeResponse buildPartial() {
      optic_fusion1.common.protos.HandshakeResponse result = new optic_fusion1.common.protos.HandshakeResponse(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.protocolVersion_ = protocolVersion_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.sessionId_ = sessionId_;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        to_bitField0_ |= 0x00000004;
      }
      result.hmacKey_ = hmacKey_;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        to_bitField0_ |= 0x00000008;
      }
      result.rsaPublicKey_ = rsaPublicKey_;
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.authenticationRequired_ = authenticationRequired_;
        to_bitField0_ |= 0x00000010;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof optic_fusion1.common.protos.HandshakeResponse) {
        return mergeFrom((optic_fusion1.common.protos.HandshakeResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(optic_fusion1.common.protos.HandshakeResponse other) {
      if (other == optic_fusion1.common.protos.HandshakeResponse.getDefaultInstance()) return this;
      if (other.hasProtocolVersion()) {
        setProtocolVersion(other.getProtocolVersion());
      }
      if (other.hasSessionId()) {
        bitField0_ |= 0x00000002;
        sessionId_ = other.sessionId_;
        onChanged();
      }
      if (other.hasHmacKey()) {
        setHmacKey(other.getHmacKey());
      }
      if (other.hasRsaPublicKey()) {
        setRsaPublicKey(other.getRsaPublicKey());
      }
      if (other.hasAuthenticationRequired()) {
        setAuthenticationRequired(other.getAuthenticationRequired());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      if (!hasProtocolVersion()) {
        return false;
      }
      if (!hasSessionId()) {
        return false;
      }
      if (!hasHmacKey()) {
        return false;
      }
      if (!hasRsaPublicKey()) {
        return false;
      }
      if (!hasAuthenticationRequired()) {
        return false;
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      optic_fusion1.common.protos.HandshakeResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (optic_fusion1.common.protos.HandshakeResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int protocolVersion_ = 1;
    /**
     * <pre>
     * The servers protocol version
     * </pre>
     *
     * <code>required .ProtocolVersion protocol_version = 1;</code>
     * @return Whether the protocolVersion field is set.
     */
    @java.lang.Override public boolean hasProtocolVersion() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * The servers protocol version
     * </pre>
     *
     * <code>required .ProtocolVersion protocol_version = 1;</code>
     * @return The protocolVersion.
     */
    @java.lang.Override
    public optic_fusion1.common.protos.ProtocolVersion getProtocolVersion() {
      @SuppressWarnings("deprecation")
      optic_fusion1.common.protos.ProtocolVersion result = optic_fusion1.common.protos.ProtocolVersion.valueOf(protocolVersion_);
      return result == null ? optic_fusion1.common.protos.ProtocolVersion.VERSION_1 : result;
    }
    /**
     * <pre>
     * The servers protocol version
     * </pre>
     *
     * <code>required .ProtocolVersion protocol_version = 1;</code>
     * @param value The protocolVersion to set.
     * @return This builder for chaining.
     */
    public Builder setProtocolVersion(optic_fusion1.common.protos.ProtocolVersion value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      protocolVersion_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The servers protocol version
     * </pre>
     *
     * <code>required .ProtocolVersion protocol_version = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearProtocolVersion() {
      bitField0_ = (bitField0_ & ~0x00000001);
      protocolVersion_ = 1;
      onChanged();
      return this;
    }

    private java.lang.Object sessionId_ = "";
    /**
     * <code>required string session_id = 2;</code>
     * @return Whether the sessionId field is set.
     */
    public boolean hasSessionId() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required string session_id = 2;</code>
     * @return The sessionId.
     */
    public java.lang.String getSessionId() {
      java.lang.Object ref = sessionId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sessionId_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string session_id = 2;</code>
     * @return The bytes for sessionId.
     */
    public com.google.protobuf.ByteString
        getSessionIdBytes() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sessionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string session_id = 2;</code>
     * @param value The sessionId to set.
     * @return This builder for chaining.
     */
    public Builder setSessionId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      sessionId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string session_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSessionId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      sessionId_ = getDefaultInstance().getSessionId();
      onChanged();
      return this;
    }
    /**
     * <code>required string session_id = 2;</code>
     * @param value The bytes for sessionId to set.
     * @return This builder for chaining.
     */
    public Builder setSessionIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      sessionId_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString hmacKey_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>required bytes hmac_key = 3;</code>
     * @return Whether the hmacKey field is set.
     */
    @java.lang.Override
    public boolean hasHmacKey() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required bytes hmac_key = 3;</code>
     * @return The hmacKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getHmacKey() {
      return hmacKey_;
    }
    /**
     * <code>required bytes hmac_key = 3;</code>
     * @param value The hmacKey to set.
     * @return This builder for chaining.
     */
    public Builder setHmacKey(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      hmacKey_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required bytes hmac_key = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearHmacKey() {
      bitField0_ = (bitField0_ & ~0x00000004);
      hmacKey_ = getDefaultInstance().getHmacKey();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString rsaPublicKey_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>required bytes rsa_public_key = 4;</code>
     * @return Whether the rsaPublicKey field is set.
     */
    @java.lang.Override
    public boolean hasRsaPublicKey() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required bytes rsa_public_key = 4;</code>
     * @return The rsaPublicKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getRsaPublicKey() {
      return rsaPublicKey_;
    }
    /**
     * <code>required bytes rsa_public_key = 4;</code>
     * @param value The rsaPublicKey to set.
     * @return This builder for chaining.
     */
    public Builder setRsaPublicKey(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      rsaPublicKey_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required bytes rsa_public_key = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearRsaPublicKey() {
      bitField0_ = (bitField0_ & ~0x00000008);
      rsaPublicKey_ = getDefaultInstance().getRsaPublicKey();
      onChanged();
      return this;
    }

    private boolean authenticationRequired_ ;
    /**
     * <code>required bool authentication_required = 5;</code>
     * @return Whether the authenticationRequired field is set.
     */
    @java.lang.Override
    public boolean hasAuthenticationRequired() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>required bool authentication_required = 5;</code>
     * @return The authenticationRequired.
     */
    @java.lang.Override
    public boolean getAuthenticationRequired() {
      return authenticationRequired_;
    }
    /**
     * <code>required bool authentication_required = 5;</code>
     * @param value The authenticationRequired to set.
     * @return This builder for chaining.
     */
    public Builder setAuthenticationRequired(boolean value) {
      bitField0_ |= 0x00000010;
      authenticationRequired_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required bool authentication_required = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearAuthenticationRequired() {
      bitField0_ = (bitField0_ & ~0x00000010);
      authenticationRequired_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:HandshakeResponse)
  }

  // @@protoc_insertion_point(class_scope:HandshakeResponse)
  private static final optic_fusion1.common.protos.HandshakeResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new optic_fusion1.common.protos.HandshakeResponse();
  }

  public static optic_fusion1.common.protos.HandshakeResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<HandshakeResponse>
      PARSER = new com.google.protobuf.AbstractParser<HandshakeResponse>() {
    @java.lang.Override
    public HandshakeResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new HandshakeResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<HandshakeResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<HandshakeResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public optic_fusion1.common.protos.HandshakeResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

