// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChatRoomProtocol.proto

package optic_fusion1.common.protos;

public interface PacketOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Packet)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required .Packet.Type packet_type = 1;</code>
   * @return Whether the packetType field is set.
   */
  boolean hasPacketType();
  /**
   * <code>required .Packet.Type packet_type = 1;</code>
   * @return The packetType.
   */
  optic_fusion1.common.protos.Packet.Type getPacketType();

  /**
   * <code>.HandshakePacket handshake_data = 3;</code>
   * @return Whether the handshakeData field is set.
   */
  boolean hasHandshakeData();
  /**
   * <code>.HandshakePacket handshake_data = 3;</code>
   * @return The handshakeData.
   */
  optic_fusion1.common.protos.HandshakePacket getHandshakeData();
  /**
   * <code>.HandshakePacket handshake_data = 3;</code>
   */
  optic_fusion1.common.protos.HandshakePacketOrBuilder getHandshakeDataOrBuilder();

  /**
   * <code>.PongPacket pong_data = 4;</code>
   * @return Whether the pongData field is set.
   */
  boolean hasPongData();
  /**
   * <code>.PongPacket pong_data = 4;</code>
   * @return The pongData.
   */
  optic_fusion1.common.protos.PongPacket getPongData();
  /**
   * <code>.PongPacket pong_data = 4;</code>
   */
  optic_fusion1.common.protos.PongPacketOrBuilder getPongDataOrBuilder();

  /**
   * <code>.ErrorPacket error_data = 5;</code>
   * @return Whether the errorData field is set.
   */
  boolean hasErrorData();
  /**
   * <code>.ErrorPacket error_data = 5;</code>
   * @return The errorData.
   */
  optic_fusion1.common.protos.ErrorPacket getErrorData();
  /**
   * <code>.ErrorPacket error_data = 5;</code>
   */
  optic_fusion1.common.protos.ErrorPacketOrBuilder getErrorDataOrBuilder();

  public optic_fusion1.common.protos.Packet.PacketDataCase getPacketDataCase();
}
