// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChatRoomProtocol.proto

package optic_fusion1.common.protos;

public interface PacketOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Packet)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required .Packet.Type packet_type = 1;</code>
   * @return Whether the packetType field is set.
   */
  boolean hasPacketType();
  /**
   * <code>required .Packet.Type packet_type = 1;</code>
   * @return The packetType.
   */
  optic_fusion1.common.protos.Packet.Type getPacketType();

  /**
   * <pre>
   * Required for all packet types other than handshake request and response
   * </pre>
   *
   * <code>optional bytes signature = 2;</code>
   * @return Whether the signature field is set.
   */
  boolean hasSignature();
  /**
   * <pre>
   * Required for all packet types other than handshake request and response
   * </pre>
   *
   * <code>optional bytes signature = 2;</code>
   * @return The signature.
   */
  com.google.protobuf.ByteString getSignature();

  /**
   * <pre>
   *  oneof packet_data { HandshakeRequest handshake_request_data = 3; HandshakeResponse handshake_response_data = 4; PingPacket ping_data = 5; PongPacket pong_data = 6; ErrorPacket error_data = 7; AuthenticationRequestPacket auth_request_data = 8;};
   * </pre>
   *
   * <code>optional bytes data = 3;</code>
   * @return Whether the data field is set.
   */
  boolean hasData();
  /**
   * <pre>
   *  oneof packet_data { HandshakeRequest handshake_request_data = 3; HandshakeResponse handshake_response_data = 4; PingPacket ping_data = 5; PongPacket pong_data = 6; ErrorPacket error_data = 7; AuthenticationRequestPacket auth_request_data = 8;};
   * </pre>
   *
   * <code>optional bytes data = 3;</code>
   * @return The data.
   */
  com.google.protobuf.ByteString getData();
}
