// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChatRoomProtocol.proto

package optic_fusion1.common.protos;

/**
 * Protobuf type {@code Packet}
 */
public final class Packet extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Packet)
    PacketOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Packet.newBuilder() to construct.
  private Packet(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Packet() {
    packetType_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Packet();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Packet(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();
              @SuppressWarnings("deprecation")
            optic_fusion1.common.protos.Packet.Type value = optic_fusion1.common.protos.Packet.Type.valueOf(rawValue);
            if (value == null) {
              unknownFields.mergeVarintField(1, rawValue);
            } else {
              bitField0_ |= 0x00000001;
              packetType_ = rawValue;
            }
            break;
          }
          case 18: {
            optic_fusion1.common.protos.HandshakeRequest.Builder subBuilder = null;
            if (packetDataCase_ == 2) {
              subBuilder = ((optic_fusion1.common.protos.HandshakeRequest) packetData_).toBuilder();
            }
            packetData_ =
                input.readMessage(optic_fusion1.common.protos.HandshakeRequest.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((optic_fusion1.common.protos.HandshakeRequest) packetData_);
              packetData_ = subBuilder.buildPartial();
            }
            packetDataCase_ = 2;
            break;
          }
          case 26: {
            optic_fusion1.common.protos.HandshakeResponse.Builder subBuilder = null;
            if (packetDataCase_ == 3) {
              subBuilder = ((optic_fusion1.common.protos.HandshakeResponse) packetData_).toBuilder();
            }
            packetData_ =
                input.readMessage(optic_fusion1.common.protos.HandshakeResponse.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((optic_fusion1.common.protos.HandshakeResponse) packetData_);
              packetData_ = subBuilder.buildPartial();
            }
            packetDataCase_ = 3;
            break;
          }
          case 34: {
            optic_fusion1.common.protos.PongPacket.Builder subBuilder = null;
            if (packetDataCase_ == 4) {
              subBuilder = ((optic_fusion1.common.protos.PongPacket) packetData_).toBuilder();
            }
            packetData_ =
                input.readMessage(optic_fusion1.common.protos.PongPacket.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((optic_fusion1.common.protos.PongPacket) packetData_);
              packetData_ = subBuilder.buildPartial();
            }
            packetDataCase_ = 4;
            break;
          }
          case 42: {
            optic_fusion1.common.protos.ErrorPacket.Builder subBuilder = null;
            if (packetDataCase_ == 5) {
              subBuilder = ((optic_fusion1.common.protos.ErrorPacket) packetData_).toBuilder();
            }
            packetData_ =
                input.readMessage(optic_fusion1.common.protos.ErrorPacket.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((optic_fusion1.common.protos.ErrorPacket) packetData_);
              packetData_ = subBuilder.buildPartial();
            }
            packetDataCase_ = 5;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return optic_fusion1.common.protos.ChatRoomProtocol.internal_static_Packet_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return optic_fusion1.common.protos.ChatRoomProtocol.internal_static_Packet_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            optic_fusion1.common.protos.Packet.class, optic_fusion1.common.protos.Packet.Builder.class);
  }

  /**
   * Protobuf enum {@code Packet.Type}
   */
  public enum Type
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>HANDSHAKE_REQUEST = 0;</code>
     */
    HANDSHAKE_REQUEST(0),
    /**
     * <code>HANDSHAKE_RESPONSE = 1;</code>
     */
    HANDSHAKE_RESPONSE(1),
    /**
     * <code>PING = 2;</code>
     */
    PING(2),
    /**
     * <code>PONG = 3;</code>
     */
    PONG(3),
    /**
     * <code>ERROR = 4;</code>
     */
    ERROR(4),
    ;

    /**
     * <code>HANDSHAKE_REQUEST = 0;</code>
     */
    public static final int HANDSHAKE_REQUEST_VALUE = 0;
    /**
     * <code>HANDSHAKE_RESPONSE = 1;</code>
     */
    public static final int HANDSHAKE_RESPONSE_VALUE = 1;
    /**
     * <code>PING = 2;</code>
     */
    public static final int PING_VALUE = 2;
    /**
     * <code>PONG = 3;</code>
     */
    public static final int PONG_VALUE = 3;
    /**
     * <code>ERROR = 4;</code>
     */
    public static final int ERROR_VALUE = 4;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Type valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Type forNumber(int value) {
      switch (value) {
        case 0: return HANDSHAKE_REQUEST;
        case 1: return HANDSHAKE_RESPONSE;
        case 2: return PING;
        case 3: return PONG;
        case 4: return ERROR;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Type>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Type> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Type>() {
            public Type findValueByNumber(int number) {
              return Type.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return optic_fusion1.common.protos.Packet.getDescriptor().getEnumTypes().get(0);
    }

    private static final Type[] VALUES = values();

    public static Type valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Type(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Packet.Type)
  }

  private int bitField0_;
  private int packetDataCase_ = 0;
  private java.lang.Object packetData_;
  public enum PacketDataCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    HANDSHAKE_REQUEST_DATA(2),
    HANDSHAKE_RESPONSE_DATA(3),
    PONG_DATA(4),
    ERROR_DATA(5),
    PACKETDATA_NOT_SET(0);
    private final int value;
    private PacketDataCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PacketDataCase valueOf(int value) {
      return forNumber(value);
    }

    public static PacketDataCase forNumber(int value) {
      switch (value) {
        case 2: return HANDSHAKE_REQUEST_DATA;
        case 3: return HANDSHAKE_RESPONSE_DATA;
        case 4: return PONG_DATA;
        case 5: return ERROR_DATA;
        case 0: return PACKETDATA_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public PacketDataCase
  getPacketDataCase() {
    return PacketDataCase.forNumber(
        packetDataCase_);
  }

  public static final int PACKET_TYPE_FIELD_NUMBER = 1;
  private int packetType_;
  /**
   * <code>required .Packet.Type packet_type = 1;</code>
   * @return Whether the packetType field is set.
   */
  @java.lang.Override public boolean hasPacketType() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>required .Packet.Type packet_type = 1;</code>
   * @return The packetType.
   */
  @java.lang.Override public optic_fusion1.common.protos.Packet.Type getPacketType() {
    @SuppressWarnings("deprecation")
    optic_fusion1.common.protos.Packet.Type result = optic_fusion1.common.protos.Packet.Type.valueOf(packetType_);
    return result == null ? optic_fusion1.common.protos.Packet.Type.HANDSHAKE_REQUEST : result;
  }

  public static final int HANDSHAKE_REQUEST_DATA_FIELD_NUMBER = 2;
  /**
   * <code>.HandshakeRequest handshake_request_data = 2;</code>
   * @return Whether the handshakeRequestData field is set.
   */
  @java.lang.Override
  public boolean hasHandshakeRequestData() {
    return packetDataCase_ == 2;
  }
  /**
   * <code>.HandshakeRequest handshake_request_data = 2;</code>
   * @return The handshakeRequestData.
   */
  @java.lang.Override
  public optic_fusion1.common.protos.HandshakeRequest getHandshakeRequestData() {
    if (packetDataCase_ == 2) {
       return (optic_fusion1.common.protos.HandshakeRequest) packetData_;
    }
    return optic_fusion1.common.protos.HandshakeRequest.getDefaultInstance();
  }
  /**
   * <code>.HandshakeRequest handshake_request_data = 2;</code>
   */
  @java.lang.Override
  public optic_fusion1.common.protos.HandshakeRequestOrBuilder getHandshakeRequestDataOrBuilder() {
    if (packetDataCase_ == 2) {
       return (optic_fusion1.common.protos.HandshakeRequest) packetData_;
    }
    return optic_fusion1.common.protos.HandshakeRequest.getDefaultInstance();
  }

  public static final int HANDSHAKE_RESPONSE_DATA_FIELD_NUMBER = 3;
  /**
   * <code>.HandshakeResponse handshake_response_data = 3;</code>
   * @return Whether the handshakeResponseData field is set.
   */
  @java.lang.Override
  public boolean hasHandshakeResponseData() {
    return packetDataCase_ == 3;
  }
  /**
   * <code>.HandshakeResponse handshake_response_data = 3;</code>
   * @return The handshakeResponseData.
   */
  @java.lang.Override
  public optic_fusion1.common.protos.HandshakeResponse getHandshakeResponseData() {
    if (packetDataCase_ == 3) {
       return (optic_fusion1.common.protos.HandshakeResponse) packetData_;
    }
    return optic_fusion1.common.protos.HandshakeResponse.getDefaultInstance();
  }
  /**
   * <code>.HandshakeResponse handshake_response_data = 3;</code>
   */
  @java.lang.Override
  public optic_fusion1.common.protos.HandshakeResponseOrBuilder getHandshakeResponseDataOrBuilder() {
    if (packetDataCase_ == 3) {
       return (optic_fusion1.common.protos.HandshakeResponse) packetData_;
    }
    return optic_fusion1.common.protos.HandshakeResponse.getDefaultInstance();
  }

  public static final int PONG_DATA_FIELD_NUMBER = 4;
  /**
   * <code>.PongPacket pong_data = 4;</code>
   * @return Whether the pongData field is set.
   */
  @java.lang.Override
  public boolean hasPongData() {
    return packetDataCase_ == 4;
  }
  /**
   * <code>.PongPacket pong_data = 4;</code>
   * @return The pongData.
   */
  @java.lang.Override
  public optic_fusion1.common.protos.PongPacket getPongData() {
    if (packetDataCase_ == 4) {
       return (optic_fusion1.common.protos.PongPacket) packetData_;
    }
    return optic_fusion1.common.protos.PongPacket.getDefaultInstance();
  }
  /**
   * <code>.PongPacket pong_data = 4;</code>
   */
  @java.lang.Override
  public optic_fusion1.common.protos.PongPacketOrBuilder getPongDataOrBuilder() {
    if (packetDataCase_ == 4) {
       return (optic_fusion1.common.protos.PongPacket) packetData_;
    }
    return optic_fusion1.common.protos.PongPacket.getDefaultInstance();
  }

  public static final int ERROR_DATA_FIELD_NUMBER = 5;
  /**
   * <code>.ErrorPacket error_data = 5;</code>
   * @return Whether the errorData field is set.
   */
  @java.lang.Override
  public boolean hasErrorData() {
    return packetDataCase_ == 5;
  }
  /**
   * <code>.ErrorPacket error_data = 5;</code>
   * @return The errorData.
   */
  @java.lang.Override
  public optic_fusion1.common.protos.ErrorPacket getErrorData() {
    if (packetDataCase_ == 5) {
       return (optic_fusion1.common.protos.ErrorPacket) packetData_;
    }
    return optic_fusion1.common.protos.ErrorPacket.getDefaultInstance();
  }
  /**
   * <code>.ErrorPacket error_data = 5;</code>
   */
  @java.lang.Override
  public optic_fusion1.common.protos.ErrorPacketOrBuilder getErrorDataOrBuilder() {
    if (packetDataCase_ == 5) {
       return (optic_fusion1.common.protos.ErrorPacket) packetData_;
    }
    return optic_fusion1.common.protos.ErrorPacket.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasPacketType()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (hasHandshakeRequestData()) {
      if (!getHandshakeRequestData().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    if (hasHandshakeResponseData()) {
      if (!getHandshakeResponseData().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    if (hasPongData()) {
      if (!getPongData().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    if (hasErrorData()) {
      if (!getErrorData().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeEnum(1, packetType_);
    }
    if (packetDataCase_ == 2) {
      output.writeMessage(2, (optic_fusion1.common.protos.HandshakeRequest) packetData_);
    }
    if (packetDataCase_ == 3) {
      output.writeMessage(3, (optic_fusion1.common.protos.HandshakeResponse) packetData_);
    }
    if (packetDataCase_ == 4) {
      output.writeMessage(4, (optic_fusion1.common.protos.PongPacket) packetData_);
    }
    if (packetDataCase_ == 5) {
      output.writeMessage(5, (optic_fusion1.common.protos.ErrorPacket) packetData_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, packetType_);
    }
    if (packetDataCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (optic_fusion1.common.protos.HandshakeRequest) packetData_);
    }
    if (packetDataCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (optic_fusion1.common.protos.HandshakeResponse) packetData_);
    }
    if (packetDataCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (optic_fusion1.common.protos.PongPacket) packetData_);
    }
    if (packetDataCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, (optic_fusion1.common.protos.ErrorPacket) packetData_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof optic_fusion1.common.protos.Packet)) {
      return super.equals(obj);
    }
    optic_fusion1.common.protos.Packet other = (optic_fusion1.common.protos.Packet) obj;

    if (hasPacketType() != other.hasPacketType()) return false;
    if (hasPacketType()) {
      if (packetType_ != other.packetType_) return false;
    }
    if (!getPacketDataCase().equals(other.getPacketDataCase())) return false;
    switch (packetDataCase_) {
      case 2:
        if (!getHandshakeRequestData()
            .equals(other.getHandshakeRequestData())) return false;
        break;
      case 3:
        if (!getHandshakeResponseData()
            .equals(other.getHandshakeResponseData())) return false;
        break;
      case 4:
        if (!getPongData()
            .equals(other.getPongData())) return false;
        break;
      case 5:
        if (!getErrorData()
            .equals(other.getErrorData())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasPacketType()) {
      hash = (37 * hash) + PACKET_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + packetType_;
    }
    switch (packetDataCase_) {
      case 2:
        hash = (37 * hash) + HANDSHAKE_REQUEST_DATA_FIELD_NUMBER;
        hash = (53 * hash) + getHandshakeRequestData().hashCode();
        break;
      case 3:
        hash = (37 * hash) + HANDSHAKE_RESPONSE_DATA_FIELD_NUMBER;
        hash = (53 * hash) + getHandshakeResponseData().hashCode();
        break;
      case 4:
        hash = (37 * hash) + PONG_DATA_FIELD_NUMBER;
        hash = (53 * hash) + getPongData().hashCode();
        break;
      case 5:
        hash = (37 * hash) + ERROR_DATA_FIELD_NUMBER;
        hash = (53 * hash) + getErrorData().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static optic_fusion1.common.protos.Packet parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static optic_fusion1.common.protos.Packet parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static optic_fusion1.common.protos.Packet parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static optic_fusion1.common.protos.Packet parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static optic_fusion1.common.protos.Packet parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static optic_fusion1.common.protos.Packet parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static optic_fusion1.common.protos.Packet parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static optic_fusion1.common.protos.Packet parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static optic_fusion1.common.protos.Packet parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static optic_fusion1.common.protos.Packet parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static optic_fusion1.common.protos.Packet parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static optic_fusion1.common.protos.Packet parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(optic_fusion1.common.protos.Packet prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Packet}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Packet)
      optic_fusion1.common.protos.PacketOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return optic_fusion1.common.protos.ChatRoomProtocol.internal_static_Packet_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return optic_fusion1.common.protos.ChatRoomProtocol.internal_static_Packet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              optic_fusion1.common.protos.Packet.class, optic_fusion1.common.protos.Packet.Builder.class);
    }

    // Construct using optic_fusion1.common.protos.Packet.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      packetType_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      packetDataCase_ = 0;
      packetData_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return optic_fusion1.common.protos.ChatRoomProtocol.internal_static_Packet_descriptor;
    }

    @java.lang.Override
    public optic_fusion1.common.protos.Packet getDefaultInstanceForType() {
      return optic_fusion1.common.protos.Packet.getDefaultInstance();
    }

    @java.lang.Override
    public optic_fusion1.common.protos.Packet build() {
      optic_fusion1.common.protos.Packet result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public optic_fusion1.common.protos.Packet buildPartial() {
      optic_fusion1.common.protos.Packet result = new optic_fusion1.common.protos.Packet(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.packetType_ = packetType_;
      if (packetDataCase_ == 2) {
        if (handshakeRequestDataBuilder_ == null) {
          result.packetData_ = packetData_;
        } else {
          result.packetData_ = handshakeRequestDataBuilder_.build();
        }
      }
      if (packetDataCase_ == 3) {
        if (handshakeResponseDataBuilder_ == null) {
          result.packetData_ = packetData_;
        } else {
          result.packetData_ = handshakeResponseDataBuilder_.build();
        }
      }
      if (packetDataCase_ == 4) {
        if (pongDataBuilder_ == null) {
          result.packetData_ = packetData_;
        } else {
          result.packetData_ = pongDataBuilder_.build();
        }
      }
      if (packetDataCase_ == 5) {
        if (errorDataBuilder_ == null) {
          result.packetData_ = packetData_;
        } else {
          result.packetData_ = errorDataBuilder_.build();
        }
      }
      result.bitField0_ = to_bitField0_;
      result.packetDataCase_ = packetDataCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof optic_fusion1.common.protos.Packet) {
        return mergeFrom((optic_fusion1.common.protos.Packet)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(optic_fusion1.common.protos.Packet other) {
      if (other == optic_fusion1.common.protos.Packet.getDefaultInstance()) return this;
      if (other.hasPacketType()) {
        setPacketType(other.getPacketType());
      }
      switch (other.getPacketDataCase()) {
        case HANDSHAKE_REQUEST_DATA: {
          mergeHandshakeRequestData(other.getHandshakeRequestData());
          break;
        }
        case HANDSHAKE_RESPONSE_DATA: {
          mergeHandshakeResponseData(other.getHandshakeResponseData());
          break;
        }
        case PONG_DATA: {
          mergePongData(other.getPongData());
          break;
        }
        case ERROR_DATA: {
          mergeErrorData(other.getErrorData());
          break;
        }
        case PACKETDATA_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      if (!hasPacketType()) {
        return false;
      }
      if (hasHandshakeRequestData()) {
        if (!getHandshakeRequestData().isInitialized()) {
          return false;
        }
      }
      if (hasHandshakeResponseData()) {
        if (!getHandshakeResponseData().isInitialized()) {
          return false;
        }
      }
      if (hasPongData()) {
        if (!getPongData().isInitialized()) {
          return false;
        }
      }
      if (hasErrorData()) {
        if (!getErrorData().isInitialized()) {
          return false;
        }
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      optic_fusion1.common.protos.Packet parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (optic_fusion1.common.protos.Packet) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int packetDataCase_ = 0;
    private java.lang.Object packetData_;
    public PacketDataCase
        getPacketDataCase() {
      return PacketDataCase.forNumber(
          packetDataCase_);
    }

    public Builder clearPacketData() {
      packetDataCase_ = 0;
      packetData_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private int packetType_ = 0;
    /**
     * <code>required .Packet.Type packet_type = 1;</code>
     * @return Whether the packetType field is set.
     */
    @java.lang.Override public boolean hasPacketType() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required .Packet.Type packet_type = 1;</code>
     * @return The packetType.
     */
    @java.lang.Override
    public optic_fusion1.common.protos.Packet.Type getPacketType() {
      @SuppressWarnings("deprecation")
      optic_fusion1.common.protos.Packet.Type result = optic_fusion1.common.protos.Packet.Type.valueOf(packetType_);
      return result == null ? optic_fusion1.common.protos.Packet.Type.HANDSHAKE_REQUEST : result;
    }
    /**
     * <code>required .Packet.Type packet_type = 1;</code>
     * @param value The packetType to set.
     * @return This builder for chaining.
     */
    public Builder setPacketType(optic_fusion1.common.protos.Packet.Type value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      packetType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>required .Packet.Type packet_type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPacketType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      packetType_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        optic_fusion1.common.protos.HandshakeRequest, optic_fusion1.common.protos.HandshakeRequest.Builder, optic_fusion1.common.protos.HandshakeRequestOrBuilder> handshakeRequestDataBuilder_;
    /**
     * <code>.HandshakeRequest handshake_request_data = 2;</code>
     * @return Whether the handshakeRequestData field is set.
     */
    @java.lang.Override
    public boolean hasHandshakeRequestData() {
      return packetDataCase_ == 2;
    }
    /**
     * <code>.HandshakeRequest handshake_request_data = 2;</code>
     * @return The handshakeRequestData.
     */
    @java.lang.Override
    public optic_fusion1.common.protos.HandshakeRequest getHandshakeRequestData() {
      if (handshakeRequestDataBuilder_ == null) {
        if (packetDataCase_ == 2) {
          return (optic_fusion1.common.protos.HandshakeRequest) packetData_;
        }
        return optic_fusion1.common.protos.HandshakeRequest.getDefaultInstance();
      } else {
        if (packetDataCase_ == 2) {
          return handshakeRequestDataBuilder_.getMessage();
        }
        return optic_fusion1.common.protos.HandshakeRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.HandshakeRequest handshake_request_data = 2;</code>
     */
    public Builder setHandshakeRequestData(optic_fusion1.common.protos.HandshakeRequest value) {
      if (handshakeRequestDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        packetData_ = value;
        onChanged();
      } else {
        handshakeRequestDataBuilder_.setMessage(value);
      }
      packetDataCase_ = 2;
      return this;
    }
    /**
     * <code>.HandshakeRequest handshake_request_data = 2;</code>
     */
    public Builder setHandshakeRequestData(
        optic_fusion1.common.protos.HandshakeRequest.Builder builderForValue) {
      if (handshakeRequestDataBuilder_ == null) {
        packetData_ = builderForValue.build();
        onChanged();
      } else {
        handshakeRequestDataBuilder_.setMessage(builderForValue.build());
      }
      packetDataCase_ = 2;
      return this;
    }
    /**
     * <code>.HandshakeRequest handshake_request_data = 2;</code>
     */
    public Builder mergeHandshakeRequestData(optic_fusion1.common.protos.HandshakeRequest value) {
      if (handshakeRequestDataBuilder_ == null) {
        if (packetDataCase_ == 2 &&
            packetData_ != optic_fusion1.common.protos.HandshakeRequest.getDefaultInstance()) {
          packetData_ = optic_fusion1.common.protos.HandshakeRequest.newBuilder((optic_fusion1.common.protos.HandshakeRequest) packetData_)
              .mergeFrom(value).buildPartial();
        } else {
          packetData_ = value;
        }
        onChanged();
      } else {
        if (packetDataCase_ == 2) {
          handshakeRequestDataBuilder_.mergeFrom(value);
        }
        handshakeRequestDataBuilder_.setMessage(value);
      }
      packetDataCase_ = 2;
      return this;
    }
    /**
     * <code>.HandshakeRequest handshake_request_data = 2;</code>
     */
    public Builder clearHandshakeRequestData() {
      if (handshakeRequestDataBuilder_ == null) {
        if (packetDataCase_ == 2) {
          packetDataCase_ = 0;
          packetData_ = null;
          onChanged();
        }
      } else {
        if (packetDataCase_ == 2) {
          packetDataCase_ = 0;
          packetData_ = null;
        }
        handshakeRequestDataBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.HandshakeRequest handshake_request_data = 2;</code>
     */
    public optic_fusion1.common.protos.HandshakeRequest.Builder getHandshakeRequestDataBuilder() {
      return getHandshakeRequestDataFieldBuilder().getBuilder();
    }
    /**
     * <code>.HandshakeRequest handshake_request_data = 2;</code>
     */
    @java.lang.Override
    public optic_fusion1.common.protos.HandshakeRequestOrBuilder getHandshakeRequestDataOrBuilder() {
      if ((packetDataCase_ == 2) && (handshakeRequestDataBuilder_ != null)) {
        return handshakeRequestDataBuilder_.getMessageOrBuilder();
      } else {
        if (packetDataCase_ == 2) {
          return (optic_fusion1.common.protos.HandshakeRequest) packetData_;
        }
        return optic_fusion1.common.protos.HandshakeRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.HandshakeRequest handshake_request_data = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        optic_fusion1.common.protos.HandshakeRequest, optic_fusion1.common.protos.HandshakeRequest.Builder, optic_fusion1.common.protos.HandshakeRequestOrBuilder> 
        getHandshakeRequestDataFieldBuilder() {
      if (handshakeRequestDataBuilder_ == null) {
        if (!(packetDataCase_ == 2)) {
          packetData_ = optic_fusion1.common.protos.HandshakeRequest.getDefaultInstance();
        }
        handshakeRequestDataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            optic_fusion1.common.protos.HandshakeRequest, optic_fusion1.common.protos.HandshakeRequest.Builder, optic_fusion1.common.protos.HandshakeRequestOrBuilder>(
                (optic_fusion1.common.protos.HandshakeRequest) packetData_,
                getParentForChildren(),
                isClean());
        packetData_ = null;
      }
      packetDataCase_ = 2;
      onChanged();;
      return handshakeRequestDataBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        optic_fusion1.common.protos.HandshakeResponse, optic_fusion1.common.protos.HandshakeResponse.Builder, optic_fusion1.common.protos.HandshakeResponseOrBuilder> handshakeResponseDataBuilder_;
    /**
     * <code>.HandshakeResponse handshake_response_data = 3;</code>
     * @return Whether the handshakeResponseData field is set.
     */
    @java.lang.Override
    public boolean hasHandshakeResponseData() {
      return packetDataCase_ == 3;
    }
    /**
     * <code>.HandshakeResponse handshake_response_data = 3;</code>
     * @return The handshakeResponseData.
     */
    @java.lang.Override
    public optic_fusion1.common.protos.HandshakeResponse getHandshakeResponseData() {
      if (handshakeResponseDataBuilder_ == null) {
        if (packetDataCase_ == 3) {
          return (optic_fusion1.common.protos.HandshakeResponse) packetData_;
        }
        return optic_fusion1.common.protos.HandshakeResponse.getDefaultInstance();
      } else {
        if (packetDataCase_ == 3) {
          return handshakeResponseDataBuilder_.getMessage();
        }
        return optic_fusion1.common.protos.HandshakeResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.HandshakeResponse handshake_response_data = 3;</code>
     */
    public Builder setHandshakeResponseData(optic_fusion1.common.protos.HandshakeResponse value) {
      if (handshakeResponseDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        packetData_ = value;
        onChanged();
      } else {
        handshakeResponseDataBuilder_.setMessage(value);
      }
      packetDataCase_ = 3;
      return this;
    }
    /**
     * <code>.HandshakeResponse handshake_response_data = 3;</code>
     */
    public Builder setHandshakeResponseData(
        optic_fusion1.common.protos.HandshakeResponse.Builder builderForValue) {
      if (handshakeResponseDataBuilder_ == null) {
        packetData_ = builderForValue.build();
        onChanged();
      } else {
        handshakeResponseDataBuilder_.setMessage(builderForValue.build());
      }
      packetDataCase_ = 3;
      return this;
    }
    /**
     * <code>.HandshakeResponse handshake_response_data = 3;</code>
     */
    public Builder mergeHandshakeResponseData(optic_fusion1.common.protos.HandshakeResponse value) {
      if (handshakeResponseDataBuilder_ == null) {
        if (packetDataCase_ == 3 &&
            packetData_ != optic_fusion1.common.protos.HandshakeResponse.getDefaultInstance()) {
          packetData_ = optic_fusion1.common.protos.HandshakeResponse.newBuilder((optic_fusion1.common.protos.HandshakeResponse) packetData_)
              .mergeFrom(value).buildPartial();
        } else {
          packetData_ = value;
        }
        onChanged();
      } else {
        if (packetDataCase_ == 3) {
          handshakeResponseDataBuilder_.mergeFrom(value);
        }
        handshakeResponseDataBuilder_.setMessage(value);
      }
      packetDataCase_ = 3;
      return this;
    }
    /**
     * <code>.HandshakeResponse handshake_response_data = 3;</code>
     */
    public Builder clearHandshakeResponseData() {
      if (handshakeResponseDataBuilder_ == null) {
        if (packetDataCase_ == 3) {
          packetDataCase_ = 0;
          packetData_ = null;
          onChanged();
        }
      } else {
        if (packetDataCase_ == 3) {
          packetDataCase_ = 0;
          packetData_ = null;
        }
        handshakeResponseDataBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.HandshakeResponse handshake_response_data = 3;</code>
     */
    public optic_fusion1.common.protos.HandshakeResponse.Builder getHandshakeResponseDataBuilder() {
      return getHandshakeResponseDataFieldBuilder().getBuilder();
    }
    /**
     * <code>.HandshakeResponse handshake_response_data = 3;</code>
     */
    @java.lang.Override
    public optic_fusion1.common.protos.HandshakeResponseOrBuilder getHandshakeResponseDataOrBuilder() {
      if ((packetDataCase_ == 3) && (handshakeResponseDataBuilder_ != null)) {
        return handshakeResponseDataBuilder_.getMessageOrBuilder();
      } else {
        if (packetDataCase_ == 3) {
          return (optic_fusion1.common.protos.HandshakeResponse) packetData_;
        }
        return optic_fusion1.common.protos.HandshakeResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.HandshakeResponse handshake_response_data = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        optic_fusion1.common.protos.HandshakeResponse, optic_fusion1.common.protos.HandshakeResponse.Builder, optic_fusion1.common.protos.HandshakeResponseOrBuilder> 
        getHandshakeResponseDataFieldBuilder() {
      if (handshakeResponseDataBuilder_ == null) {
        if (!(packetDataCase_ == 3)) {
          packetData_ = optic_fusion1.common.protos.HandshakeResponse.getDefaultInstance();
        }
        handshakeResponseDataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            optic_fusion1.common.protos.HandshakeResponse, optic_fusion1.common.protos.HandshakeResponse.Builder, optic_fusion1.common.protos.HandshakeResponseOrBuilder>(
                (optic_fusion1.common.protos.HandshakeResponse) packetData_,
                getParentForChildren(),
                isClean());
        packetData_ = null;
      }
      packetDataCase_ = 3;
      onChanged();;
      return handshakeResponseDataBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        optic_fusion1.common.protos.PongPacket, optic_fusion1.common.protos.PongPacket.Builder, optic_fusion1.common.protos.PongPacketOrBuilder> pongDataBuilder_;
    /**
     * <code>.PongPacket pong_data = 4;</code>
     * @return Whether the pongData field is set.
     */
    @java.lang.Override
    public boolean hasPongData() {
      return packetDataCase_ == 4;
    }
    /**
     * <code>.PongPacket pong_data = 4;</code>
     * @return The pongData.
     */
    @java.lang.Override
    public optic_fusion1.common.protos.PongPacket getPongData() {
      if (pongDataBuilder_ == null) {
        if (packetDataCase_ == 4) {
          return (optic_fusion1.common.protos.PongPacket) packetData_;
        }
        return optic_fusion1.common.protos.PongPacket.getDefaultInstance();
      } else {
        if (packetDataCase_ == 4) {
          return pongDataBuilder_.getMessage();
        }
        return optic_fusion1.common.protos.PongPacket.getDefaultInstance();
      }
    }
    /**
     * <code>.PongPacket pong_data = 4;</code>
     */
    public Builder setPongData(optic_fusion1.common.protos.PongPacket value) {
      if (pongDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        packetData_ = value;
        onChanged();
      } else {
        pongDataBuilder_.setMessage(value);
      }
      packetDataCase_ = 4;
      return this;
    }
    /**
     * <code>.PongPacket pong_data = 4;</code>
     */
    public Builder setPongData(
        optic_fusion1.common.protos.PongPacket.Builder builderForValue) {
      if (pongDataBuilder_ == null) {
        packetData_ = builderForValue.build();
        onChanged();
      } else {
        pongDataBuilder_.setMessage(builderForValue.build());
      }
      packetDataCase_ = 4;
      return this;
    }
    /**
     * <code>.PongPacket pong_data = 4;</code>
     */
    public Builder mergePongData(optic_fusion1.common.protos.PongPacket value) {
      if (pongDataBuilder_ == null) {
        if (packetDataCase_ == 4 &&
            packetData_ != optic_fusion1.common.protos.PongPacket.getDefaultInstance()) {
          packetData_ = optic_fusion1.common.protos.PongPacket.newBuilder((optic_fusion1.common.protos.PongPacket) packetData_)
              .mergeFrom(value).buildPartial();
        } else {
          packetData_ = value;
        }
        onChanged();
      } else {
        if (packetDataCase_ == 4) {
          pongDataBuilder_.mergeFrom(value);
        }
        pongDataBuilder_.setMessage(value);
      }
      packetDataCase_ = 4;
      return this;
    }
    /**
     * <code>.PongPacket pong_data = 4;</code>
     */
    public Builder clearPongData() {
      if (pongDataBuilder_ == null) {
        if (packetDataCase_ == 4) {
          packetDataCase_ = 0;
          packetData_ = null;
          onChanged();
        }
      } else {
        if (packetDataCase_ == 4) {
          packetDataCase_ = 0;
          packetData_ = null;
        }
        pongDataBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.PongPacket pong_data = 4;</code>
     */
    public optic_fusion1.common.protos.PongPacket.Builder getPongDataBuilder() {
      return getPongDataFieldBuilder().getBuilder();
    }
    /**
     * <code>.PongPacket pong_data = 4;</code>
     */
    @java.lang.Override
    public optic_fusion1.common.protos.PongPacketOrBuilder getPongDataOrBuilder() {
      if ((packetDataCase_ == 4) && (pongDataBuilder_ != null)) {
        return pongDataBuilder_.getMessageOrBuilder();
      } else {
        if (packetDataCase_ == 4) {
          return (optic_fusion1.common.protos.PongPacket) packetData_;
        }
        return optic_fusion1.common.protos.PongPacket.getDefaultInstance();
      }
    }
    /**
     * <code>.PongPacket pong_data = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        optic_fusion1.common.protos.PongPacket, optic_fusion1.common.protos.PongPacket.Builder, optic_fusion1.common.protos.PongPacketOrBuilder> 
        getPongDataFieldBuilder() {
      if (pongDataBuilder_ == null) {
        if (!(packetDataCase_ == 4)) {
          packetData_ = optic_fusion1.common.protos.PongPacket.getDefaultInstance();
        }
        pongDataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            optic_fusion1.common.protos.PongPacket, optic_fusion1.common.protos.PongPacket.Builder, optic_fusion1.common.protos.PongPacketOrBuilder>(
                (optic_fusion1.common.protos.PongPacket) packetData_,
                getParentForChildren(),
                isClean());
        packetData_ = null;
      }
      packetDataCase_ = 4;
      onChanged();;
      return pongDataBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        optic_fusion1.common.protos.ErrorPacket, optic_fusion1.common.protos.ErrorPacket.Builder, optic_fusion1.common.protos.ErrorPacketOrBuilder> errorDataBuilder_;
    /**
     * <code>.ErrorPacket error_data = 5;</code>
     * @return Whether the errorData field is set.
     */
    @java.lang.Override
    public boolean hasErrorData() {
      return packetDataCase_ == 5;
    }
    /**
     * <code>.ErrorPacket error_data = 5;</code>
     * @return The errorData.
     */
    @java.lang.Override
    public optic_fusion1.common.protos.ErrorPacket getErrorData() {
      if (errorDataBuilder_ == null) {
        if (packetDataCase_ == 5) {
          return (optic_fusion1.common.protos.ErrorPacket) packetData_;
        }
        return optic_fusion1.common.protos.ErrorPacket.getDefaultInstance();
      } else {
        if (packetDataCase_ == 5) {
          return errorDataBuilder_.getMessage();
        }
        return optic_fusion1.common.protos.ErrorPacket.getDefaultInstance();
      }
    }
    /**
     * <code>.ErrorPacket error_data = 5;</code>
     */
    public Builder setErrorData(optic_fusion1.common.protos.ErrorPacket value) {
      if (errorDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        packetData_ = value;
        onChanged();
      } else {
        errorDataBuilder_.setMessage(value);
      }
      packetDataCase_ = 5;
      return this;
    }
    /**
     * <code>.ErrorPacket error_data = 5;</code>
     */
    public Builder setErrorData(
        optic_fusion1.common.protos.ErrorPacket.Builder builderForValue) {
      if (errorDataBuilder_ == null) {
        packetData_ = builderForValue.build();
        onChanged();
      } else {
        errorDataBuilder_.setMessage(builderForValue.build());
      }
      packetDataCase_ = 5;
      return this;
    }
    /**
     * <code>.ErrorPacket error_data = 5;</code>
     */
    public Builder mergeErrorData(optic_fusion1.common.protos.ErrorPacket value) {
      if (errorDataBuilder_ == null) {
        if (packetDataCase_ == 5 &&
            packetData_ != optic_fusion1.common.protos.ErrorPacket.getDefaultInstance()) {
          packetData_ = optic_fusion1.common.protos.ErrorPacket.newBuilder((optic_fusion1.common.protos.ErrorPacket) packetData_)
              .mergeFrom(value).buildPartial();
        } else {
          packetData_ = value;
        }
        onChanged();
      } else {
        if (packetDataCase_ == 5) {
          errorDataBuilder_.mergeFrom(value);
        }
        errorDataBuilder_.setMessage(value);
      }
      packetDataCase_ = 5;
      return this;
    }
    /**
     * <code>.ErrorPacket error_data = 5;</code>
     */
    public Builder clearErrorData() {
      if (errorDataBuilder_ == null) {
        if (packetDataCase_ == 5) {
          packetDataCase_ = 0;
          packetData_ = null;
          onChanged();
        }
      } else {
        if (packetDataCase_ == 5) {
          packetDataCase_ = 0;
          packetData_ = null;
        }
        errorDataBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.ErrorPacket error_data = 5;</code>
     */
    public optic_fusion1.common.protos.ErrorPacket.Builder getErrorDataBuilder() {
      return getErrorDataFieldBuilder().getBuilder();
    }
    /**
     * <code>.ErrorPacket error_data = 5;</code>
     */
    @java.lang.Override
    public optic_fusion1.common.protos.ErrorPacketOrBuilder getErrorDataOrBuilder() {
      if ((packetDataCase_ == 5) && (errorDataBuilder_ != null)) {
        return errorDataBuilder_.getMessageOrBuilder();
      } else {
        if (packetDataCase_ == 5) {
          return (optic_fusion1.common.protos.ErrorPacket) packetData_;
        }
        return optic_fusion1.common.protos.ErrorPacket.getDefaultInstance();
      }
    }
    /**
     * <code>.ErrorPacket error_data = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        optic_fusion1.common.protos.ErrorPacket, optic_fusion1.common.protos.ErrorPacket.Builder, optic_fusion1.common.protos.ErrorPacketOrBuilder> 
        getErrorDataFieldBuilder() {
      if (errorDataBuilder_ == null) {
        if (!(packetDataCase_ == 5)) {
          packetData_ = optic_fusion1.common.protos.ErrorPacket.getDefaultInstance();
        }
        errorDataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            optic_fusion1.common.protos.ErrorPacket, optic_fusion1.common.protos.ErrorPacket.Builder, optic_fusion1.common.protos.ErrorPacketOrBuilder>(
                (optic_fusion1.common.protos.ErrorPacket) packetData_,
                getParentForChildren(),
                isClean());
        packetData_ = null;
      }
      packetDataCase_ = 5;
      onChanged();;
      return errorDataBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Packet)
  }

  // @@protoc_insertion_point(class_scope:Packet)
  private static final optic_fusion1.common.protos.Packet DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new optic_fusion1.common.protos.Packet();
  }

  public static optic_fusion1.common.protos.Packet getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<Packet>
      PARSER = new com.google.protobuf.AbstractParser<Packet>() {
    @java.lang.Override
    public Packet parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Packet(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Packet> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Packet> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public optic_fusion1.common.protos.Packet getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

