// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChatRoomProtocol.proto

package optic_fusion1.common.protos;

public interface PingPacketOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PingPacket)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string session_id = 2;</code>
   * @return Whether the sessionId field is set.
   */
  boolean hasSessionId();
  /**
   * <code>required string session_id = 2;</code>
   * @return The sessionId.
   */
  java.lang.String getSessionId();
  /**
   * <code>required string session_id = 2;</code>
   * @return The bytes for sessionId.
   */
  com.google.protobuf.ByteString
      getSessionIdBytes();
}
